export const SORT_BY_PROXIMITY_OPTION = 'nearby';

export const SORT_BY_MOST_RECENTLY_VALIDATED_OPTION = 'recentlyUpdated';

export const SORT_BY_MOST_SERVICES_OPTION = 'mostServices';

export const SORT_BY_OPTIONS = [
  SORT_BY_PROXIMITY_OPTION,
  SORT_BY_MOST_RECENTLY_VALIDATED_OPTION,
  SORT_BY_MOST_SERVICES_OPTION,
];
